export const categories = [
  { id: "all", label: "All Events", icon: "🎉" },
  { id: "music", label: "Music", icon: "🎵" },
  { id: "tech", label: "Technology", icon: "💻" },
  { id: "food", label: "Food & Drinks", icon: "🍷" },
  { id: "sports", label: "Sports", icon: "⚽" },
  { id: "art", label: "Art & Culture", icon: "🎨" },
  { id: "business", label: "Business", icon: "💼" },
  { id: "health", label: "Health & Wellness", icon: "🧘" },
];

export const events = [
  {
    id: "1",
    title: "Neon Nights Music Festival 2026",
    category: "music",
    date: "2026-09-15",
    time: "18:00",
    endTime: "23:59",
    location: "Amphitheater Park, Los Angeles",
    city: "Los Angeles",
    country: "USA",
    image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80",
      "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80",
      "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800&q=80",
    ],
    description: "Experience the ultimate music festival under the neon-lit sky. Featuring over 50 artists across 5 stages, food trucks from 20 local vendors, and an unforgettable atmosphere that combines art, technology, and music.",
    longDescription: "Neon Nights Music Festival is the biggest music event of the year on the West Coast. Join thousands of music lovers for an epic 2-day celebration featuring chart-topping headliners, emerging indie artists, and legendary performers. The festival grounds will be transformed into an immersive neon wonderland with state-of-the-art light installations, interactive art exhibits, and gourmet food villages. Don't miss the once-in-a-lifetime experience!",
    organizer: "Stellar Events Co.",
    organizerAvatar: "SE",
    featured: true,
    trending: true,
    tags: ["festival", "live music", "outdoor", "multi-day"],
    ticketTypes: [
      { id: "ga", name: "General Admission", price: 89, available: 500, description: "Access to all main stages" },
      { id: "vip", name: "VIP Experience", price: 249, available: 100, description: "Front row access + exclusive lounge + meet & greet" },
      { id: "group", name: "Group Pack (5+)", price: 69, available: 200, description: "Per ticket, min. 5 tickets" },
    ],
    rating: 4.8,
    reviews: 1240,
    attendees: 8500,
    capacity: 10000,
  },
  {
    id: "2",
    title: "TechForward Summit 2026",
    category: "tech",
    date: "2026-09-22",
    time: "09:00",
    endTime: "18:00",
    location: "Moscone Center, San Francisco",
    city: "San Francisco",
    country: "USA",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80",
      "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800&q=80",
      "https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=800&q=80",
    ],
    description: "The premier technology conference for innovators, developers, and entrepreneurs. 3 days of keynotes, workshops, and networking with industry leaders.",
    longDescription: "TechForward Summit brings together the brightest minds in technology for three days of immersive learning, collaboration, and inspiration. Featuring over 200 speakers, 100+ sessions, and hands-on workshops covering AI, blockchain, cloud computing, cybersecurity, and emerging technologies. Connect with 5,000+ professionals and discover the innovations shaping tomorrow.",
    organizer: "TechVentures Inc.",
    organizerAvatar: "TV",
    featured: true,
    trending: false,
    tags: ["conference", "networking", "AI", "innovation"],
    ticketTypes: [
      { id: "standard", name: "Standard Pass", price: 299, available: 800, description: "Access to all sessions and exhibits" },
      { id: "pro", name: "Pro Pass", price: 599, available: 200, description: "All sessions + workshops + speaker dinners" },
      { id: "enterprise", name: "Enterprise Pass", price: 1299, available: 50, description: "5 passes + private meeting rooms + VIP access" },
    ],
    rating: 4.9,
    reviews: 892,
    attendees: 4200,
    capacity: 5000,
  },
  {
    id: "3",
    title: "International Food & Wine Expo",
    category: "food",
    date: "2026-09-28",
    time: "11:00",
    endTime: "21:00",
    location: "Convention Center, New York",
    city: "New York",
    country: "USA",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
      "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80",
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
    ],
    description: "Sample cuisines from over 40 countries, attend live cooking demonstrations, and discover rare wines from top vineyards around the world.",
    longDescription: "The International Food & Wine Expo is a celebration of global culinary excellence. Explore pavilions from over 40 countries, taste authentic dishes prepared by Michelin-starred chefs, and participate in exclusive wine tasting sessions guided by master sommeliers. This annual event draws food enthusiasts, culinary professionals, and travel lovers from around the globe.",
    organizer: "Global Gastronomy Events",
    organizerAvatar: "GG",
    featured: false,
    trending: true,
    tags: ["food", "wine", "culture", "tasting"],
    ticketTypes: [
      { id: "day", name: "Day Pass", price: 45, available: 1000, description: "Full day access to all pavilions" },
      { id: "tasting", name: "Tasting Package", price: 89, available: 300, description: "Day pass + 10 exclusive tastings" },
      { id: "vip", name: "Chef's Table VIP", price: 199, available: 50, description: "Private chef's table dinner + all access" },
    ],
    rating: 4.7,
    reviews: 2100,
    attendees: 6800,
    capacity: 8000,
  },
  {
    id: "4",
    title: "Urban Art Exhibition: Beyond Boundaries",
    category: "art",
    date: "2026-10-05",
    time: "10:00",
    endTime: "20:00",
    location: "The Modern Gallery, Chicago",
    city: "Chicago",
    country: "USA",
    image: "https://images.unsplash.com/photo-1578926288207-a90a5366b235?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1578926288207-a90a5366b235?w=800&q=80",
      "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&q=80",
      "https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=800&q=80",
    ],
    description: "An immersive contemporary art exhibition showcasing 200+ works from 80 artists across 6 continents, challenging the boundaries of perception and reality.",
    longDescription: "Beyond Boundaries is a landmark exhibition that brings together groundbreaking contemporary artists from around the world. Experience installations that challenge your perception, paintings that tell untold stories, and sculptures that defy physical limits. The exhibition runs for 6 weeks and features interactive workshops, artist talks, and guided tours for all experience levels.",
    organizer: "The Modern Gallery",
    organizerAvatar: "MG",
    featured: false,
    trending: false,
    tags: ["art", "contemporary", "exhibition", "culture"],
    ticketTypes: [
      { id: "general", name: "General Admission", price: 25, available: 2000, description: "Full exhibition access" },
      { id: "guided", name: "Guided Tour", price: 45, available: 100, description: "Expert-guided 2hr tour" },
      { id: "vip", name: "Opening Night VIP", price: 150, available: 30, description: "Preview night + cocktails + artist meet & greet" },
    ],
    rating: 4.6,
    reviews: 445,
    attendees: 1200,
    capacity: 2000,
  },
  {
    id: "5",
    title: "Champions League Final Watch Party",
    category: "sports",
    date: "2026-10-12",
    time: "19:00",
    endTime: "23:00",
    location: "Sports Arena, Miami",
    city: "Miami",
    country: "USA",
    image: "https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?w=800&q=80",
      "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&q=80",
      "https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=800&q=80",
    ],
    description: "Watch the biggest game of the year on a 40-foot LED screen with 2,000 fellow fans. Includes free drinks, halftime show, and prize draws.",
    longDescription: "Join us for the ultimate Champions League Final watch party experience! Set in the state-of-the-art Sports Arena, this event promises an electrifying atmosphere with a massive 40-foot 4K LED screen, surround sound, and non-stop entertainment. Enjoy unlimited drinks for the first hour, live commentary from local sports legends, halftime performances, and amazing prize giveaways including VIP trips to next year's final.",
    organizer: "Sports Fanatics Events",
    organizerAvatar: "SF",
    featured: false,
    trending: true,
    tags: ["sports", "football", "watch party", "social"],
    ticketTypes: [
      { id: "standard", name: "Fan Seat", price: 35, available: 1500, description: "General seating + 1 complimentary drink" },
      { id: "premium", name: "Premium Section", price: 75, available: 300, description: "Premium seating + unlimited drinks first hour" },
      { id: "vip", name: "Skybox VIP", price: 199, available: 50, description: "Private skybox + open bar + gourmet food" },
    ],
    rating: 4.5,
    reviews: 678,
    attendees: 1800,
    capacity: 2000,
  },
  {
    id: "6",
    title: "Startup Founders Summit",
    category: "business",
    date: "2026-10-18",
    time: "08:30",
    endTime: "17:00",
    location: "The Grand Hotel, Austin",
    city: "Austin",
    country: "USA",
    image: "https://images.unsplash.com/photo-1556761175-4b46a572b786?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1556761175-4b46a572b786?w=800&q=80",
      "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80",
      "https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=800&q=80",
    ],
    description: "Connect with 500+ startup founders, investors, and mentors. Pitch competitions, fireside chats, and curated networking sessions with top VCs.",
    longDescription: "The Startup Founders Summit is where the next generation of company builders comes to learn, connect, and grow. Hear from founders who've built billion-dollar companies, engage with leading venture capitalists, and participate in our signature pitch competition with $500,000 in prizes. Whether you're pre-seed or Series B, this is the event that can change your trajectory.",
    organizer: "Founders Club Global",
    organizerAvatar: "FC",
    featured: true,
    trending: false,
    tags: ["startup", "entrepreneurship", "investors", "networking"],
    ticketTypes: [
      { id: "founder", name: "Founder Pass", price: 199, available: 400, description: "Full day access + networking lunch" },
      { id: "investor", name: "Investor Pass", price: 499, available: 100, description: "All access + private meeting room + featured directory" },
      { id: "pitch", name: "Pitch Competition", price: 99, available: 50, description: "Compete for $500k in prizes" },
    ],
    rating: 4.8,
    reviews: 334,
    attendees: 420,
    capacity: 500,
  },
  {
    id: "7",
    title: "Mindfulness & Wellness Retreat",
    category: "health",
    date: "2026-10-24",
    time: "07:00",
    endTime: "18:00",
    location: "Sunrise Resort, Sedona",
    city: "Sedona",
    country: "USA",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80",
      "https://images.unsplash.com/photo-1545389336-cf090694435e?w=800&q=80",
      "https://images.unsplash.com/photo-1588286840104-8957b019727f?w=800&q=80",
    ],
    description: "A transformative day retreat in the heart of Sedona's red rocks. Yoga, meditation, breathwork sessions, and holistic wellness workshops.",
    longDescription: "Escape the noise of modern life and reconnect with yourself at our all-day Mindfulness & Wellness Retreat. Nestled in the breathtaking red rock landscape of Sedona, Arizona, this retreat offers expert-led yoga sessions at sunrise, guided meditation, sound healing ceremonies, breathwork with certified practitioners, and organic farm-to-table meals. Leave feeling restored, recharged, and renewed.",
    organizer: "Zen Path Retreats",
    organizerAvatar: "ZP",
    featured: false,
    trending: false,
    tags: ["wellness", "yoga", "meditation", "retreat"],
    ticketTypes: [
      { id: "standard", name: "Day Retreat", price: 149, available: 60, description: "Full day access + 2 meals" },
      { id: "weekend", name: "Weekend Retreat", price: 399, available: 20, description: "2 days + accommodation + all meals" },
    ],
    rating: 4.9,
    reviews: 215,
    attendees: 55,
    capacity: 60,
  },
  {
    id: "8",
    title: "Jazz Under the Stars",
    category: "music",
    date: "2026-11-01",
    time: "20:00",
    endTime: "23:30",
    location: "Riverside Park, Nashville",
    city: "Nashville",
    country: "USA",
    image: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&q=80",
      "https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=800&q=80",
      "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=800&q=80",
    ],
    description: "An intimate outdoor jazz concert featuring Grammy-winning artists performing classic and contemporary jazz under a canopy of stars.",
    longDescription: "Jazz Under the Stars is Nashville's most beloved annual outdoor concert. This year, we're celebrating our 10th anniversary with an extraordinary lineup of Grammy-winning jazz legends and rising stars. Bring a blanket, enjoy gourmet picnic boxes, and let the music transport you under Nashville's beautiful night sky. A perfect evening for music lovers of all ages.",
    organizer: "Nashville Jazz Society",
    organizerAvatar: "NJ",
    featured: false,
    trending: false,
    tags: ["jazz", "outdoor", "intimate", "live music"],
    ticketTypes: [
      { id: "lawn", name: "Lawn Pass", price: 55, available: 600, description: "Open lawn seating + BYO blanket" },
      { id: "reserved", name: "Reserved Seating", price: 95, available: 200, description: "Reserved chair seating + welcome drink" },
      { id: "vip", name: "VIP Tent", price: 185, available: 40, description: "VIP tent + gourmet picnic box + champagne" },
    ],
    rating: 4.7,
    reviews: 567,
    attendees: 700,
    capacity: 800,
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Sarah Mitchell",
    role: "Event Organizer",
    avatar: "SM",
    content: "EventHub transformed how we manage ticket sales. We sold out our 2,000-seat venue in 48 hours — something that used to take weeks!",
    rating: 5,
  },
  {
    id: 2,
    name: "James Rodriguez",
    role: "Festival Attendee",
    avatar: "JR",
    content: "The booking experience is seamless. I can find events I love, compare ticket options, and check out in under a minute. It's brilliant.",
    rating: 5,
  },
  {
    id: 3,
    name: "Priya Sharma",
    role: "Corporate Event Manager",
    avatar: "PS",
    content: "Managing 500+ attendee conferences was stressful until we found EventHub. The dashboard gives me everything I need in one place.",
    rating: 5,
  },
];

export const stats = [
  { label: "Events Hosted", value: "12,400+", icon: "🎪" },
  { label: "Happy Attendees", value: "2.8M+", icon: "😊" },
  { label: "Cities Worldwide", value: "180+", icon: "🌍" },
  { label: "Organizers Trust Us", value: "8,500+", icon: "🤝" },
];

export function getEventById(id) {
  return events.find((e) => e.id === id);
}

export function getRelatedEvents(event) {
  return events
    .filter((e) => e.id !== event.id && e.category === event.category)
    .slice(0, 3);
}

export function formatDate(dateString) {
  const date = new Date(dateString);
  return date.toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

export function formatShortDate(dateString) {
  const date = new Date(dateString);
  return date.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}
